server:
  port: 8888
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  application:
    name: search-provider

mybatis:
  mapper-locations: classpath*:com/gpmall/search/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.search.dal.entitys

